name: CI

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Name'
        required: true
      password:
        description: 'Password'
        required: true

jobs:
  authenticate_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate
        run: |
          INPUT_HASH=$(echo -n "${{ github.event.inputs.username }}:${{ github.event.inputs.password }}" | sha256sum | awk '{print $1}')
          echo "Input Hash: $INPUT_HASH"  # Debug: Show the computed hash of the input
          IFS=',' read -ra HASHES <<< "${{ secrets.HASH_CREDENTIALS }}"
          AUTHENTICATED="false"
          for HASH in "${HASHES[@]}"; do
            IFS=':' read -r USERNAME HASHED_PASS <<< "$HASH"
            echo "Checking against stored hash for $USERNAME"  # Debug: Show which user is being checked
            if [[ "${{ github.event.inputs.username }}" == "$USERNAME" && "$INPUT_HASH" == "$HASHED_PASS" ]]; then
              AUTHENTICATED="true"
              break
            fi
          done
      
          if [[ "$AUTHENTICATED" == "true" ]]; then
            echo "Authentication successful."
          else
            echo "Authentication failed."
            exit 1
          fi

      - name: Set up git with GitHub Token
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global --add safe.directory '*'
          git remote set-url origin https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/${{ github.repository }}

      - name: Push files to production
        run: |
          git push https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/Osiris-B/workflow-test-2.git main:main
