name: Push to Production Fork

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username for authentication'
        required: true
      password:
        description: 'Password for authentication'
        required: true

jobs:
  authenticate_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Dev Repo Main Branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Authenticate
      id: auth_step
      run: |
        INPUT_HASH=$(echo -n "${{ github.event.inputs.username }}:${{ github.event.inputs.password }}" | sha256sum | awk '{print $1}')
        echo "Input Hash: $INPUT_HASH"
        IFS=',' read -ra HASHES <<< "${{ secrets.HASH_CREDENTIALS }}"
        AUTHENTICATED="false"
        for HASH in "${HASHES[@]}"; do
          IFS=':' read -r USERNAME HASHED_PASS <<< "$HASH"
          if [[ "${{ github.event.inputs.username }}" == "$USERNAME" && "$INPUT_HASH" == "$HASHED_PASS" ]]; then
            AUTHENTICATED="true"
            break
          fi
        done

        if [[ "$AUTHENTICATED" == "true" ]]; then
          echo "Authentication successful."
        else
          echo "Authentication failed."
          exit 1
        fi

    - name: Setup SSH
      if: success()
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa
        eval "$(ssh-agent -s)"
        ssh-add id_rsa
        mkdir -p ~/.ssh  # Ensure the .ssh directory exists
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Push to Main Branch of Prod Fork
      if: success()
      run: |
        git remote add production-fork git@github.com:Osiris-B/workflow-test-2.git
        git push -f production-fork main:main
