name: Push to Production Fork

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username for authentication'
        required: true
      password:
        description: 'Password for authentication'
        required: true

jobs:
  push_to_prod_fork:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Current Repo Main Branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Authenticate
      id: auth_step
      run: |
        INPUT_HASH=$(echo -n "${{ github.event.inputs.username }}:${{ github.event.inputs.password }}" | sha256sum | awk '{print $1}')
        echo "Input Hash: $INPUT_HASH"
        IFS=',' read -ra HASHES <<< "${{ secrets.HASH_CREDENTIALS }}"
        AUTHENTICATED="false"
        for HASH in "${HASHES[@]}"; do
          IFS=':' read -r USERNAME HASHED_PASS <<< "$HASH"
          if [[ "${{ github.event.inputs.username }}" == "$USERNAME" && "$INPUT_HASH" == "$HASHED_PASS" ]]; then
            AUTHENTICATED="true"
            break
          fi
        done

        if [[ "$AUTHENTICATED" == "true" ]]; then
          echo "Authentication successful."
        else
          echo "Authentication failed."
          exit 1
        fi

    - name: Push to Production Repo Main Branch
      run: |
        git remote add production-fork https://$GITHUB_ACTOR:${{ secrets.API_TOKEN_2 }}@github.com/Osiris-B/workflow-test-2.git
        git push -f production-fork main:main
