name: Push to Production Fork

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Name'
        required: true
      password:
        description: 'Password'
        required: true

jobs:
  authenticate_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Dev Repo Main Branch
      uses: actions/checkout@v3
      with:
        ref: main  # Ensures that the main branch of the dev repo is checked out

    - name: Authenticate
      run: |
        INPUT_HASH=$(echo -n "${{ github.event.inputs.username }}:${{ github.event.inputs.password }}" | sha256sum | awk '{print $1}')
        echo "Input Hash: $INPUT_HASH"  # Debug: Show the computed hash of the input
        IFS=',' read -ra HASHES <<< "${{ secrets.HASH_CREDENTIALS }}"
        AUTHENTICATED="false"
        for HASH in "${HASHES[@]}"; do
          IFS=':' read -r USERNAME HASHED_PASS <<< "$HASH"
          echo "Checking against stored hash for $USERNAME"  # Debug: Show which user is being checked
          if [[ "${{ github.event.inputs.username }}" == "$USERNAME" && "$INPUT_HASH" == "$HASHED_PASS" ]]; then
            AUTHENTICATED="true"
            break
          fi
        done

        if [[ "$AUTHENTICATED" == "true" ]]; then
          echo "Authentication successful."
        else
          echo "Authentication failed."
          exit 1
        fi

    - name: Push to Main Branch of Prod Fork
      env:
        PAT_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        git remote add production-fork https://Osiris-B:${{ secrets.API_TOKEN_GITHUB }}@github.com/Osiris-B/workflow-test-2.git
        git push -f production-fork main:main
